export const enum ERROR {
  INVALID_USERNAME = 'INVALID_USERNAME',
  INVALID_USERNAME_PASSWORD = 'INVALID_USERNAME_PASSWORD',
  INVALID_PASSWORD_RULE = 'INVALID_PASSWORD_RULE',
  USER_ALREADY_ONLINE = 'USER_ALREADY_ONLINE',
}
